org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mixin_version = 0.8.5

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

modId=wares
modName=Wares: Repackaged
modLicense=MIT
modVersion=1.0.0
modGroupId=com.flarelabsmc
modAuthors=sentwayfarer, mortuusars
modDescription=Villager trades with extra steps.

minecraftVersion=1.21.1
minecraftVersionRange=[1.21,1.21.1)
neoVersion=21.1.199
neoVersionRange=[21.1.0,)
loaderVersionRange=[4,)

kubejsVersion=2101.7.2-build.315
rhinoVersion=2101.2.7-build.81